# Generated by Django 2.2.6 on 2019-10-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
