# Generated by Django 2.2.6 on 2019-11-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_hotel_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobilnumber', models.IntegerField(max_length=14)),
                ('message', models.TextField()),
            ],
        ),
    ]
