# Generated by Django 2.2.6 on 2019-11-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='mobilnumber',
            new_name='mobilenumber',
        ),
    ]
