# Generated by Django 2.2.6 on 2019-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20191107_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='mobilenumber',
            field=models.CharField(max_length=14),
        ),
    ]
