# Generated by Django 2.2.6 on 2019-11-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20191107_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageslider', models.ImageField(blank=True, null=True, upload_to='imageslider/')),
            ],
        ),
    ]
