# Generated by Django 2.2.6 on 2019-11-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
