# Generated by Django 2.2.6 on 2019-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
