# Generated by Django 2.2.6 on 2019-11-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('imageslider', models.ImageField(blank=True, null=True, upload_to='imageslider/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
