# Generated by Django 2.2.6 on 2019-11-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191110_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgroundimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageslider', models.ImageField(blank=True, null=True, upload_to='backgroundimage/')),
            ],
        ),
    ]
