# Generated by Django 2.2.6 on 2019-11-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_backgroundimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundimage',
            old_name='imageslider',
            new_name='image',
        ),
    ]
